pub const INSTRUCTIONS: &str = r#"Create palette-constrained retro game art; you are the user's interface. Before creating or editing, read dotmend://guides/editing with resources/read and the relevant tools/list schemas. MCP uses request metadata, never connection history.

PROJECT
Work is stored in .dotmend/ under the launch project (or explicit --workspace). Connections in the same project share art and its screen; different projects have independent work. Use project-relative image paths.

INPUT
For a PNG: (1) inspect an existing target art or create_art with supplied target constraints and initial={kind:"fill",index:<allowed index>}; target colors use #RRGGBB and transparent_index. (2) Call prepare_image with that art_id as target_art_id, a source_path relative to the server workspace, and explicit crop, resize, alpha, color_mapping and dither settings. Path errors provide the workspace and recovery steps. (3) Use the returned art_id for inspection, validation, editing and presentation. Preserve supplied constraints; ask for missing required target conditions. Use create_art with bundle_path for exported Dotmend art, or target and initial.kind=indices for caller-supplied index data.

WORKBENCH
Choose a fresh random control_id per independent task; retain it across calls and connections. At every follow-up and before agent or external work, call open_workbench with that ID and work_state:"working". This holds the screen even between calls and throughout lengthy external generation. At handoff or while awaiting user input, call open_workbench with work_state:"waiting" and share only the URL returned by that call, never a cached URL. On failure or interruption, switch to waiting or close. Also pass its workbench_id to present_art {control_id,workbench_id,view} and close_workbench. Keep control IDs private.
One controller per workspace; four workbenches per shared runtime directory. Never bypass control or limits with shell servers, PIDs or alternate paths. A working task stays active until its owner changes state or the host exits; you must clear working when work stops because external cancellation is not automatically observable. In waiting, successful presentation, human actions and real browser input renew activity; art calls, failures, inspect_workbench, HTTP/browser polling and playback do not. The default waiting idle timeout is 30 minutes. Close when finished, never while the human is working. Art and drafts persist; after shutdown reopen, inspect preserved work and share the newly returned URL.

HUMAN SCREEN
At first handoff, briefly explain available controls in the user's language: palette + click/drag paints; Mark issues: left adds, right removes; Undo once for the last stroke (Ctrl/Cmd+Z); Save (Ctrl/Cmd+S). For more than 20 allowed colors, explain that the screen shows common colors and opens in Mark issues mode. Invite the user to mark changes; read the saved concerns, focus those areas and make edits within the request's permissions. Clarify ambiguous intent. Offer older results through conversation. Repeat only when needed. Prepare collections, filters, past art, reference crops and known-time playback yourself.
Read inspect_presentation; copy current IDs into view.expected_presentation_id/expected_state_id (both explicit null only for the first view). saved.art_ids holds the explicit save; state.art_ids may contain a newer draft. state.concerns and saved.concerns identify marked candidates and pixels; marks request observation, not edit permission or rejection.
For alternatives, create distinct candidates and offer their static, read-only art items through view.candidate_choices={item_indices:[...]}. The human can choose several, change the choice, and Save. Briefly explain this in their language. Read saved.chosen_candidates ({item_index,art_id}) with saved.state_id before continuing; state.chosen_candidates is a draft. Missing or empty means no choice. Refine the saved choices as separate branches and present the next alternatives. Preserve unchosen candidates; a choice is a direction for further work, not final acceptance or rejection.

EDIT AND RECOVER
Read the request and target. Preserve palette order, duplicate indices, transparency, dimensions and constraints. validate_art locations and focus_art grant no write permission. Pass request_id for protection; preview sets before applying the exact plan and bindings.
Await dependent calls. Edit immutable candidates, compare, revalidate and submit_edit_result. After conflicts or lost responses, inspect control and durable state before retrying; never replay stale edits.
review_edit_result records only the user's expressed judgment. Saving, submission, validation, acceptance and game verification are separate; report only observed stages."#;
